repos:
  - repo: local
    hooks:
      - name: isort
        id: isort
        entry: isort ./src
        language: python
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
      - id: black
        args:
          - --line-length=88
        name: black
        entry: black
        language: python
        types: [python]
      - name: ruff (docstring)
        id: ruff-docstring
        entry: ruff check --select D,DOC --fix --config ruff.toml
        language: python
        types: [python]
      - name: bandit
        id: bandit
        args: ["-ll", "-c", ".banditrc"]
        entry: bandit
        language: python
        types: [python]
      - name: pylint
        id: pylint
        entry: env PYTHONPATH=src pylint src
        args: ["--rcfile=.pylintrc"]
        language: python
        types: [python]
