{
 "title": "template fastapi",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total INFO",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"server_template\"} |= \"INFO\"[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "Total WARNING",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"server_template\"} |= \"WARNNING\"[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "Total ERROR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"server_template\"} |= \"ERROR\"[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "Total CRITICAL",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"server_template\"} |= \"CRITICAL\"[$__range])) or vector(0)"
    }
   ]
  },
  {
   "title": "INFO Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"server_template\"} |= \"INFO\""
    }
   ]
  },
  {
   "title": "WARNING Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"server_template\"} |= \"WARNING\""
    }
   ]
  },
  {
   "title": "ERROR Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"server_template\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "CRITICAL Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"server_template\"} |= \"CRITICAL\""
    }
   ]
  },
  { "title": "App metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "POST requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{method=\"POST\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GET requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{method=\"GET\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{method=\"PUT\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATCH requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{method=\"PATCH\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{method=\"DELETE\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"template_fastapi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean POST requests time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_seconds_sum{method=\"POST\"}[$__rate_interval])) / sum(increase(http_request_duration_seconds_count{method=\"POST\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean GET requests time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_seconds_sum{method=\"GET\"}[$__rate_interval])) / sum(increase(http_request_duration_seconds_count{method=\"GET\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean PUT requests time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_seconds_sum{method=\"PUT\"}[$__rate_interval])) / sum(increase(http_request_duration_seconds_count{method=\"PUT\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean PATCH requests time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_seconds_sum{method=\"PATCH\"}[$__rate_interval])) / sum(increase(http_request_duration_seconds_count{method=\"PATCH\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean DELETE requests time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_seconds_sum{method=\"DELETE\"}[$__rate_interval])) / sum(increase(http_request_duration_seconds_count{method=\"DELETE\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - app_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{method=\"POST\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{method=\"GET\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{method=\"PUT\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PATCH requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{method=\"PATCH\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{method=\"DELETE\"}[$__range])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}